services:
  api:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 5000
    ports:
      - "5051:5000"

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    depends_on:
      - api
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    profiles:
      - tunnel
